# Don't change this! Version used to track needed updates.
version = 0
enableLootDrops = true
enableLootInVillages = true
standardLootTableWeight = 0.1
rareLootTableWeight = 0.4
runicLootTableWeight = 0.7
uniqueLootTableWeight = 0.3
enableContainedRemnants = true
disabledUniqueWeaponLoot = [  ]

[uniqueLootTableOptions]
"minecraft:entities/wither" = 5.0
"minecraft:entities/ender_dragon" = 50.0
"minecraft:chests/ruined_portal" = 3.0
"minecraft:chests/village/village_armorer" = 1.0
"minecraft:chests/village/village_butcher" = 1.0
"minecraft:chests/village/village_cartographer" = 1.0
"minecraft:chests/village/village_desert_house" = 1.0
"minecraft:chests/village/village_fisher" = 1.0
"minecraft:chests/village/village_fletcher" = 1.0
"minecraft:chests/village/village_mason" = 1.0
"minecraft:chests/village/village_plains_house" = 1.0
"minecraft:chests/village/village_savanna_house" = 1.0
"minecraft:chests/village/village_shepherd" = 1.0
"minecraft:chests/village/village_snowy_house" = 1.0
"minecraft:chests/village/village_taiga_house" = 1.0
"minecraft:chests/village/village_tannery" = 1.0
"minecraft:chests/village/village_temple" = 1.0
"minecraft:chests/village/village_toolsmith" = 1.0
"minecraft:chests/village/village_weaponsmith" = 1.0