#Dark Doppelganger Configuration
[dark_doppelganger]
	#Health of the Dark Doppelganger
	# Default: 600.0
	# Range: 1.0 ~ 100000.0
	health = 1500.0
	#Attack Damage of the Dark Doppelganger
	# Default: 10.0
	# Range: 0.1 ~ 1000.0
	attack_damage = 10.0
	#Movement Speed of the Dark Doppelganger
	# Default: 0.2
	# Range: 0.01 ~ 2.0
	movement_speed = 0.2
	#Knockback Resistance of the Dark Doppelganger
	# Default: 0.6
	# Range: 0.0 ~ 1.0
	knockback_resistance = 0.6
	#Armor of the Dark Doppelganger
	# Default: 10.0
	# Range: 0.0 ~ 100.0
	armor = 10.0
	#Follow Range of the Dark Doppelganger
	# Default: 64.0
	# Range: 1.0 ~ 256.0
	follow_range = 64.0
	#Hard mode of the Dark Doppelganger
	hard_mode = true
	#Armor item IDs the boss is NOT allowed to copy from the player. Supports wildcard with * suffix.
	#Examples:
	#minecraft:netherite_helmet
	#irons_spellbooks:*
	banned_armor = ["minecraft:netherite_helmet"]

	[dark_doppelganger.phase1]
		spells_a = ["irons_spellbooks:guiding_bolt", "irons_spellbooks:blood_needles", "irons_spellbooks:blood_slash"]
		spells_b = ["irons_spellbooks:fang_ward", "irons_spellbooks:gust"]
		spells_c = ["irons_spellbooks:burning_dash"]
		spells_d = ["irons_spellbooks:blight", "irons_spellbooks:invisibility"]

	[dark_doppelganger.phase2]
		spells_a = ["irons_spellbooks:magic_arrow", "irons_spellbooks:poison_arrow", "irons_spellbooks:magma_bomb"]
		spells_b = ["irons_spellbooks:heat_surge", "irons_spellbooks:flaming_strike"]
		spells_c = ["irons_spellbooks:frost_step"]
		spells_d = ["irons_spellbooks:root", "irons_spellbooks:thunderstorm"]

	[dark_doppelganger.phase3]
		spells_a = ["irons_spellbooks:lightning_lance", "irons_spellbooks:stomp"]
		spells_b = ["irons_spellbooks:shockwave", "irons_spellbooks:ascension"]
		spells_c = ["irons_spellbooks:blood_step"]
		spells_d = ["irons_spellbooks:evasion", "irons_spellbooks:echoing_strikes"]

	[dark_doppelganger.final]
		spells_a = ["irons_spellbooks:eldritch_blast", "irons_spellbooks:sonic_boom", "irons_spellbooks:abyssal_shroud", "irons_spellbooks:ray_of_frost", "irons_spellbooks:sculk_tentacles"]
		spells_b = ["irons_spellbooks:ascension", "irons_spellbooks:abyssal_shroud"]
		spells_c = ["irons_spellbooks:blood_step"]
		spells_d = ["irons_spellbooks:abyssal_shroud", "irons_spellbooks:echoing_strikes", "irons_spellbooks:root", "irons_spellbooks:blight"]

#Minion Configuration
[minion]
	#Base max health for minions
	# Default: 40.0
	# Range: 1.0 ~ 1000.0
	health = 40.0
	#Base attack damage for minions
	# Default: 6.0
	# Range: 0.1 ~ 100.0
	attack_damage = 6.0
	#Base movement speed for minions
	# Default: 0.28
	# Range: 0.01 ~ 2.0
	movement_speed = 0.28
	#Base armor for minions
	# Default: 4.0
	# Range: 0.0 ~ 100.0
	armor = 4.0
	#Spell used for the minion barrage goal. Must be a valid spell id.
	#Example: irons_spellbooks:devour
	barrage_spell = "irons_spellbooks:devour"
	#List of spells minions can randomly use in their attack goal.
	#Invalid ids are ignored.
	spells = ["irons_spellbooks:guiding_bolt", "irons_spellbooks:blood_needles", "irons_spellbooks:blood_slash", "irons_spellbooks:fang_ward", "irons_spellbooks:gust", "irons_spellbooks:burning_dash", "irons_spellbooks:blight", "irons_spellbooks:invisibility"]
