#When this setting is enabled, audio cues in the minigame will be louder and other sounds will be muted.
isolateAudioCues = false
#When this setting is enabled, the fishing minigame will pause the world in singleplayer.
pauseDuringMinigame = true
