#The minimum accuracy that grants an item of quality 1.
# Default: 0.75
# Range: 0.0 ~ 1.0
quality1Threshold = 0.75
#The minimum accuracy that grants an item of quality 2.
# Default: 0.9
# Range: 0.0 ~ 1.0
quality2Threshold = 0.9
#The minimum accuracy that grants an item of quality 3.
# Default: 1.0
# Range: 0.0 ~ 1.0
quality3Threshold = 1.0
#The multiplier that is applied to experience gained from fishing a quality 1 reward.
# Default: 1.5
# Range: 1.0 ~ 10.0
quality1Multiplier = 1.5
#The multiplier that is applied to experience gained from fishing a quality 2 reward.
# Default: 2.5
# Range: 1.0 ~ 10.0
quality2Multiplier = 2.5
#The multiplier that is applied to experience gained from fishing a quality 3 reward.
# Default: 4.0
# Range: 1.0 ~ 10.0
quality3Multiplier = 4.0
#The multiplier that is applied to the time it takes for a fish to bite after casting your rod.
# Default: 0.8
# Range: 0.0 ~ 1.0
biteTimeMultiplier = 0.8
#The chance for finding a treasure chest each time you play the fishing minigame.
# Default: 0.15
# Range: 0.0 ~ 1.0
treasureChestChance = 0.15
#The chance that a treasure chest found in the fishing minigame is a golden chest.
# Default: 0.1
# Range: 0.0 ~ 1.0
goldenChestChance = 0.1
#Whether it be possible to attach bobber items by hovering over a fishing rod in an inventory and right clicking.
inventoryBobberEquipping = true
#Whether legendary fish will have a strobe effect when moving in the minigame.
legendaryFishFlashing = true
#The chance that any fish that bites is a legendary fish.
# Default: 0.01
# Range: 0.0 ~ 1.0
legendaryFishChance = 0.01
